import type { Metadata } from "next";
import "../globals.css";
import GlobalState from "@/app/context";
import { Navbar } from "@/components/navbar/Navbar";
import { Footer } from "@/components/Footer";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GlobalState>
    <html lang="en">
      <body
       >
        <div className="flex flex-col min-h-screen">
           <SessionProvider>
        <Navbar/>
         <div className="flex-1 bg-[#F4F4F0]">
          {children}
         </div>
        <Footer />
        </SessionProvider>
        </div>
      </body>
    </html>
    </GlobalState>
  );
}
